content:
  path: ../example/docs # Path where md files are located
  git:
    repo: https://github.com/life-and-dev/md-site # If missing, assume content is part of this git repo
    branch: main
    path: ../example # Path where git content is cloned/checked out
features:
  bibleTooltips: true
siteName: 'Example Site'
themes:
  light:
    colors:
      primary: '#802020'
      secondary: '#ffffff'
      selected: '#802020'
      error: '#d64d5b'
      warning: '#c29e4a'
      info: '#548af7'
      success: '#6aab73'
      background: '#f9f9f9'
      surface: '#ffffff'
      surface-rail: '#f5f5f5'
      surface-appbar: '#f0f0f0'
      on-surface-rail: '#2a2a2a'
      on-surface-appbar: '#000000'
      on-background: '#292929'
      on-surface: '#292929'
      on-primary: '#ffffff'
      on-secondary: '#ffffff'
      on-selectable: '#292929'
      on-selected: '#ffffff'
      on-error: '#ffffff'
      on-warning: '#ffffff'
      on-info: '#ffffff'
      on-success: '#ffffff'
      outline: '#d7d7d7'
      outline-bars: '#f4f4f4'
  dark:
    colors:
      primary: '#af5f5f'
      secondary: '#302d2b'
      selected: '#af5f5f'
      error: '#d64d5b'
      warning: '#c29e4a'
      info: '#548af7'
      success: '#6aab73'
      background: '#161616'
      surface: '#0d0d0d'
      surface-rail: '#252525'
      surface-appbar: '#282828'
      on-surface-rail: '#d0d0d0'
      on-surface-appbar: '#ffffff'
      on-background: '#d1d1d1'
      on-surface: '#d1d1d1'
      on-primary: '#111111'
      on-secondary: '#111111'
      on-selectable: '#d1d1d1'
      on-selected: '#ffffff'
      on-error: '#ffffff'
      on-warning: '#ffffff'
      on-info: '#ffffff'
      on-success: '#ffffff'
      outline: '#303030'
      outline-bars: '#161616'
